### ISSUE TITLE
Extending the DataONE formats vocabulary

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/community-calls#1]
## Topic Description

To increase interoperability across the network, DataONE provides an [object format service](https://cn.dataone.org/cn/v2/formats) that provides a consistent vocabulary for the types of data and metadata objects that are available from repositories. Each data file or metadata file is associated with one of these object format identifiers, which provides our web interface and other client tools the information needed to properly process and parse the format. The object format vocabulary is extensible, and so we could review upcoming proposed extensions to the vocabulary, discuss the process for proposing extensions, and identify additional formats that would be useful. In addition, we could discuss whether the object format vocabulary should be modified to include URIs for each vocabulary term, and whether it should be published in RDF or OWL in a system like the ESIP [Community Ontology Repository](https://cor.esipfed.org/). 

## Relationship to DataONE?

These object formats are used by all repositories in the DataONE network, and so maintenance and extension of the vocabulary is a key aspect of interoperability among repositories. Repository and data system managers would be interested in the process for extending the service.

## Possible speakers

- Matt Jones @mbjones, on the object format revision process
- Timothy Whiteaker @twhiteaker, on the use of standardized format lists in LTER
- Possibly another speaker on the relationship to other format vocabularies like ProNOM, UDFR, and GDFR

## Related resources and links

- Object Format Service: https://cn.dataone.org/cn/v2/formats
- Object Formats Repository: https://github.com/DataONEorg/object-formats/
- ESIP [Community Ontology Repository](https://cor.esipfed.org/)

**Comment by aebudden** [comment]
Changing the status to indicate that this community call topic will move forward. Scheduled for Nov 5th.

**Comment by aebudden** [comment]
**Date/Time: Thu Nov 5th 0900 UTC**
To join this call, see the zoom link at [https://www.dataone.org/community-calls/community-call-vocab/](https://www.dataone.org/community-calls/community-call-vocab/). 
Meeting notes can be access [here](https://github.com/DataONEorg/community-calls/blob/master/notes/20201105_call_notes.md). Live collaborative note taking occurs via Hackpad [here](https://hackmd.io/DJM08xWQQc6B2qy3dby0fw)
