### ISSUE TITLE
Data Licensing: Public-domain, Attribution, and Share-alike - what license will meet your needs?

### ISSUE THREAD

**Issue by karlbenedict** [DataONEorg/community-calls#10]
## Topic Description
The selection of licenses for data and metadata hosted in repositories, shared by researchers, and reused by end users necessarily reflects an attempt to balance a variety of interests. A sample of these interests includes researcher interest in receiving proper attribution for their work in creating data, sponsor interests in maximizing the impact of the support they provide, repository interests in having the necessary rights to manage and provide access to data and metadata they host, and end user interests in being able to use the data they find with minimal restrictions and requirements. This DataONE Community Call will bring together the community and a group of invited participants to discuss the lessons learned and decisions made in selecting data licenses for use in a variety of contexts. 

## Relationship to DataONE?
The DataONE community includes the full range of participants in the creation, discovery, access, and reuse of environmental data and has a significant interest in identifying the appropriate licensing models that can meet the diverse interests of the community as a whole. 

## Possible speakers
Marty Downs (LTER)
Tracy Teal (Dryad)

## Contributing panelists
Will Cross (NCSU)
Ken Casey (NOAA / ESIP)
Kevin Ashely (JISC / DCC)

## Related resources and links
https://www.dcc.ac.uk/sites/default/files/documents/publications/reports/guides/How_To_License_Research_Data.pdf 
http://opendefinition.org/licenses/
https://resources.data.gov/open-licenses/

**Comment by karlbenedict** [comment]
Marty Downs is confirmed.

**Comment by mbjones** [comment]
@karlbenedict Folks have also recommended Katie Fortney at CDL who has written really relevant blogs on [data ownership](https://osc.universityofcalifornia.edu/2016/09/who-owns-your-data/) and [CC-BY for data](https://osc.universityofcalifornia.edu/2016/09/cc-by-and-data-not-always-a-good-fit/). Can we include those resources in our pre-call meeting links please?

**Comment by mbjones** [comment]
Also, her blog reminded me about this great PLOS article on data licensing. Can we add it to the resources?

- Carroll MW (2015) Sharing Research Data and Intellectual Property Law: A Primer. PLOS Biology, 13(8):e1002235. https://doi.org/10.1371/journal.pbio.1002235

**Comment by mbjones** [comment]
Another set of interesting resources on the licensing topic:

1) A very nice presentaiton on licensing issues for research compendia: https://www.rd-alliance.org/sites/default/files/2019-04-03_RDA_IG-Legal-Interoperability_ResearchCompendium.pdf 
2) RDA interest group: https://rd-alliance.org/groups/rdacodata-legal-interoperability-ig.html

**Comment by olendorf** [comment]
Unfortunately Will Cross was already committed. I reached out to 3 others as well and also no luck.  Unless someone else has a person in mind, I don't think we'll get a lawyer type for this.

**Comment by aebudden** [comment]
HackPad: https://hackmd.io/dpQ2gMlWTRGXzUTtnAfrjg
Zoom link: https://ucsb.zoom.us/j/94309556242
