### ISSUE TITLE
User experience to enhance DataONE community

### ISSUE THREAD

**Issue by karlbenedict** [DataONEorg/community-calls#2]
## Topic Description
A focus on this topic (possibly recurring) would provide an opportunity for demonstrating and interacting with new/emerging capabilities in DataONE platforms and services. These interactions will be followed by a discussion by the participants to provide actionable feedback to the developers to help guide current and future development activities. 

## Relationship to DataONE?
This activity has a direct impact on the use and usability of DataONE platforms, services, and tools and will provide for direct interaction between developers and users of DataONE platforms, services, and tools. 

## Possible speakers
DataONE developers

**Comment by s-allard** [comment]
We (Rachel V, Amy F and Suzie A) would like to take on this topic. We would like to do it for January (Jan 7, 1400 UTC). This will cover how UX can help repositories and researchers using DataONE examples. It will also introduce the “UX freebie” that comes with being a DataONE member.  It would include discussion with attendees about UX ideas they want to learn about/pursue. We can provide an abstract later.

**Comment by s-allard** [comment]
Here us our abstract: 
How much do you think about your users’ experiences?  Are you building data products that address your users’ needs? The User-eXperience Lab (UXL) at the University of Tennessee performs UX testing to improve how users interact with technology. The UXL has been working with DataONE and the RDM community for over a decade to help create better products that engage and empower users and stakeholders.   Join us at the  DataONE Community Call on January 7 for  a conversation about the current state of UX in the DataONE community and how we can increase data usage, improve user satisfaction and trust in repositories, and help data organizations make development decisions that save time and money.

**Comment by karlbenedict** [comment]
We will promote this for the Jan 7 call.

**Comment by rvolentine** [comment]
Hi Karl,  Amy and I worked on our slide deck, and we are hoping to change our title (and the title on the website) to: User experience to enhance DataONE community.

**Comment by mbjones** [comment]
@aebudden has been handling the web site updates, so @rvolentine please work that out with her.

I went ahead and made the title change in this issue.

**Comment by aebudden** [comment]
@rvolentine: the title on the website has been changed.

**Comment by aebudden** [comment]
The collaborative note taking hack pad is available at: https://hackmd.io/uLOuwR1bTWCZ_rqDsft6aQ
The zoom link will be posted to this issue, on the public webpage and to the hacked 10 minutes in advance of the call start time.

**Comment by aebudden** [comment]
Zoom information: https://ucsb.zoom.us/j/94309556242
