### ISSUE TITLE
Training materials and opportunities

### ISSUE THREAD

**Issue by karlbenedict** [DataONEorg/community-calls#4]
## Topic Description
This topic will highlight the training materials and opportunities supported by:

* DataONE's [*Data Management Skill Building Hub*](https://dataoneorg.github.io/Education/) managed for community contributions through the corresponding [GitHub Repository](https://github.com/DataONEorg/Education).
* ESIP's [*Data Management Training Clearinghouse*](http://dmtclearinghouse.esipfed.org) (DMTC)

## Relationship to DataONE?
The educational materials developed by the DataONE project, and available for community contributions can support a wide variety of training needs by the DataONE community. The curated collection externally developed training resources discoverable through the DMTC provides a complementary selection of materials that are discoverable using criteria such as target audience, disciplinary focus, topic, and license terms. 

## Possible speakers

* Amber Budden
* Karl Benedict
 

## Related resources and links

* DataONE *Data Management Skill Building Hub*: [https://dataoneorg.github.io/Education/](https://dataoneorg.github.io/Education/)
* DataONE Data Management Skill Building Hub GitHub repository: [https://github.com/DataONEorg/Education](https://github.com/DataONEorg/Education)
* ESIP's *Data Management Training Clearinghouse* [http://dmtclearinghouse.esipfed.org](http://dmtclearinghouse.esipfed.org)

**Comment by mbjones** [comment]
@karlbenedict I would also include our NCEAS short course curriculum in the mix, as its really relevant to delivery of trainings in a virtual setting. We've been modifying it for the virtual format and now have delivered it twice in the last month: https://www.nceas.ucsb.edu/learning-hub/courses

**Comment by aebudden** [comment]
It would also be great timing to introduce the RDMLA materials since the Skillbuilding unit will have just been completed. So maybe extending out from DataONE to community initiatives in support of RDM training? With a focus on collaboration and potentially integration? e.g. ESIP data Stewardship activity is exploring revisiting / revising the short courses but don't want to duplicate effort.

**Comment by aebudden** [comment]
Date/Time: Thu Dec 3rd 2400 UTC 1600 Pacific
To join this call, see the zoom link at https://www.dataone.org/community-calls/rdm-training/. It will be live 10 minutes before the start of the meeting.
Live collaborative note taking occurs via Hackpad [here](https://hackmd.io/GZA_3hBjR0WfZy-G3ZL-ww?both)

**Comment by aebudden** [comment]
Zoom:  https://ucsb.zoom.us/j/89546416167

**Comment by karlbenedict** [comment]
It's telling me the meeting is scheduled for 12/2. Is that expected?


Thanks,
Karl

Karl Benedict
Director of Research Data Services/ Director of IT
College of University Libraries and Learning Sciences
University of New Mexico

Office: Centennial Science and Engineering Library, Room L173

Make an Appointment: https://outlook.office365.com/owa/calendar/KarlBenedict@unmm.onmicrosoft.com/bookings/
