### ISSUE TITLE
How can DataONE interact with emerging networks - what mutual benefits can we achieve through coordinated efforts?

### ISSUE THREAD

**Issue by karlbenedict** [DataONEorg/community-calls#7]
## Topic Description
Potential benefits of network connectivity

Panel and town hall model

## Relationship to DataONE?
There is already a substantial overlap between the DataONE community and other networks, and an explicit discussion about how the networks can enjoy mutual benefits from more direct interactions can (hopefully) build on these individual connections.

**Comment by karlbenedict** [comment]
Potential networks and representatives
 - Arctic - Mark Parsons
 - EDI - Margaret O'Brien
 - LTER - Kristin Vanderbuilt
 - ESIP - Megan Carter
 - EarthCube (CDF?) - Mike Daniels or Steven Richards
 - DataONE - Matt Jones

Possibly the beginning of an ongoing internetwork dialog. Topics.

**Comment by mbjones** [comment]
- Pip Bricher - POLDER Polar data federation
- Jeff Horsburgh or Kerstin Lehnert for CZO

**Comment by karlbenedict** [comment]
Requests sent:
Kerstin Lehnert
Mike Daniels
Megan Carter & Susan Shingledecker
Margaret O'Brien
Pip Bricher

**Comment by karlbenedict** [comment]
We plan on structuring the call as follows:
 
1. 10-20 minutes of introductions from the panelists (depending on how many participate)
2. 20-30 minutes of open discussion about connectivity and collaboration opportunities
3. 10 minutes discussing next steps to move forward on near-term opportunities for network collaboration

**Comment by aebudden** [comment]
Scheduled for Thu 2/4 at 1600 Pacific 2400 UTC. To do:
- [ ] Update website (Karl)
- [ ] Send out email (Amber)
- [ ] Post to social media (Amber)

**Comment by aebudden** [comment]
Zoom line: 
https://ucsb.zoom.us/j/94309556242

Hackpad: 
https://hackmd.io/npMXMuvsTAuXHC8-mjomkQ
