### ISSUE TITLE
science on schema.org guidelines

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/community-calls#8]
## Topic Description

This could be an overview of the SOSO guidelines, and some case studies of implementation. https://science-on-schema.org

- repository implementation and its issues
- collection implementation at the Dataset level
- new features from 1.2
- what should DataONE do in terms of metadata quality checks for schema.org?
- should DataONE harvest all repos that it can, or still keep only harvesting those that request it?

There are lots of other sub topics, need to determine what is of interest for discussion.

## Relationship to DataONE?

DataONE harvests schema.org, so this affects metadata quality

## Possible speakers

- SOSO cluster members, @ashepherd
- Dryad as a repository being harvested that way
- BCO-DMO
- Open Topography
- DanBri
- Polar Data community implementors
- Chantelle for their Primer document

## Related resources and links

- https://schema.org
- https://science-on-schema.org
-

**Comment by aebudden** [comment]
Scheduling for Mar 4th

**Comment by aebudden** [comment]
To do:
- [ ] Title
- [ ] Short abstract
- [ ] Long abstract
- [ ] Speaker names
- [ ] Speaker bios 
- [ ] Speaker headshots
- [ ] Relevant twitter accounts to tag
- [ ] Website updated
- [ ] News item sent out

**Comment by datadavev** [comment]
Draft abstract:

Schema.org provides a simple mechanism to include machine readable, structured metadata in human readable web pages. The metadata is readily accessible using common web tools, and is actively harvested by large scale, generalist, commercial indexers (e.g. Google). DataONE will soon be indexing schema.org metadata as an alternative pathway for repositories to participate in the DataONE federation. The flexibility of schema.org means it can be used to describe many resources including scientific datasets, but that flexibility also enables potentially incompatible approaches for constructing such metadata. The ESIP Science-On-Schema.org group has produced an evolving set of guidelines to assist with consistent implementation of scientific dataset descriptions using the schema.org vocabulary. This community call will introduce the Science-on-schema.org guidelines, highlight additional resources available for working with schema.org, and include experiences of some that have implemented the guidelines for their repositories.

**Comment by mbjones** [comment]
Looks great! Can we add an explicit mention of Dataset? e.g.:

> Schema.org provides a simple mechanism to include machine readable, structured metadata in human readable web pages, including descriptions of Dataset entries on dataset landing pages.

**Comment by karlbenedict** [comment]
I've set up the preview page for next week's call - [https://preview.dataone.org/community-calls/soso/](https://preview.dataone.org/community-calls/soso/)

Are there additional speakers/speaker bios/headshots I should add? So far I just have Dave.

**Comment by aebudden** [comment]
Link to hacked notes for the call today: https://hackmd.io/vUhA2UV2QkOJNuFEmtXs7w
Zoom line for the call today: https://ucsb.zoom.us/j/94309556242
